spring:
  application:
    name: toby
  datasource:
    url: jdbc:mysql://localhost:3306/springbook
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: optional:classpath:db/data.sql